project:
  type: website
  output-dir: docs

website:
  search: false
  navbar:
    style: "docked"
    left:
      - text: Mael Astruc--Le Souder
        href: "index.qmd"
    right:
      - text: "Research"
        href: research.qmd
      - text: "CV"
        menu:
          - text: "EN"
            href: files/Mael_Astruc__Le_Souder_CV-en.pdf
            target: _blank
          - text: "FR"
            href: files/Mael_Astruc__Le_Souder_CV-fr.pdf
            target: _blank

theme:
  dark: darkly
  light: flatly
