project:
  type: website
  output-dir: docs

website:
  title: "Mael Astruc--Le Souder"
  search: false

format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 2000px
      margin-width: 400px
      gutter-width: 1.5rem
    theme: sandstone
    css: styles.css
    toc: true

editor: visual
