project:
  type: website
  output-dir: ../docs

website:
  search: false
  favicon: img/favicon.svg

format:
  html:
    theme: none
    minimal: true
    css:
      - styles/style.css
      - styles/header.css
    include-before-body: _includes/header.html
    title-block-style: none
    