project:
  type: website
  output-dir: ../docs

website:
  search: false

format:
  html:
    template: _includes\template.html
    minimal: true
    favicon: ./img/favicon.svg
    css:
      - styles/style.css
      - styles/header.css
    scripts:
      - scripts/script.js
    include-before-body: _includes/header.html
    